#sudo: required
os: linux
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

cache: pip
sudo: required


addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran

before_install:

  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh > tmp.txt && echo "alive";

  - bash anaconda.sh -b -p $HOME/anaconda > tmp.txt && echo "alive"
  - export PATH="$HOME/anaconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge

  - conda create -q --name=raredecay-env python=$TRAVIS_PYTHON_VERSION root > tmp.txt && echo "alive"
  - source activate raredecay-env

  # install test environment
  - conda install -y coverage > tmp.txt && echo "alive"
  - conda install -y future > tmp.txt && echo "alive"
  - pip install coveralls > tmp.txt && echo "alive"

install:
  - pip install .[all]
script:

  - coverage run -m unittest discover
  - coverage run --branch -m unittest discover


after_success:
  - coveralls

deploy:
  provider: pypi
  user: mayou36
  password:
    secure: mKCnjcpHm5DQHsCcbwo4ahx4Bz5th4gpzXZSQZOhhzs3l1mRxVDYW1GW5FjwSseftjSPXWI3EaDVbLyFP6uwTc0w+HIEeCZMVVKhb9BPWNM/a31uhYfKPwNIORqyvwsq5v4HLg5oyyMlcbNESEx6dStaqlCBOWJUeRq4tZR+R+qttIAH0lWY+QNBc7BB+hTqyZdcYF8iOo5FQBdrfG4rttie1eBEzW1t0TKURnfwx9CryCRfPdKPJi6I4O5gpaTX8h/vAhXQlWGNpSj3EkfZgn//oivnPcwjeQ2Ff8veUShB4fLJ/360xmZEEB3pxBZsb9Beq6iuNOKKtKpXVkWA+i8cPkZ7Y0USwY2quGSZsR0ztthaY8Ju2OqM+YIHchE//jQpMw8OmjcMEplFQZIezzOc/A2W0Zg+MPhFVg4zUxvg7ubHHXEYFGNarGxN2JDIkPfjstX05Stm5aH71zkV2WoyVdb3fpWd9koNJiAaWTHSCMD55pIv90jQG5Rw3Enzi2MfqdXWRs848CqoscaZ8kP4gA/BFDFcXdsP2pWGM829ndqsw0iuDn+tvY/33Dty3NNl+KfBUBrEjO3iSva0M0aIFfj3dZlP57uFK3kdGycDtm6vG5YjAgX1shpu/OiLxxN69p+T+eeDTMaFR4rKc1oLOznhZwojIf6W9aJSXF0=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8" && $TRAVIS_OS_NAME = "linux"
