#sudo: required
os: linux
language: python
python:
 - '2.7'
 - '3.4'
# - '3.5'
# - '3.6'
#matrix:
# include:
#  - os: osx
#    language: generic

cache: pip

before_install:

#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
#  sudo apt-get -qq update;
#
#  sudo apt-get install python-dev libblas-dev libatlas-dev liblapack-dev gfortran g++ python-setuptools;
#  sudo apt-get install libpng-dev libjpeg8-dev libfreetype6-dev libxft-dev;
#  fi

- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh -O anaconda.sh;
        MAYOU_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MAYOU_PYTHON_VERSION="3.4";
        wget https://repo.continuum.io/archive/Anaconda3-4.4.0-MacOSX-x86_64.sh -O anaconda.sh;
  fi
#        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
#        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O anaconda.sh;


- bash anaconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda update conda -y
- conda update anaconda -y

- conda info -a

- conda config --add channels https://conda.anaconda.org/NLeSC
#- conda config --add channels https://conda.anaconda.org/nlesc/label/dev

- conda create -q --name=raredecay-env python=$MAYOU_PYTHON_VERSION root=6
- source activate raredecay-env

# install test environment
- conda install -y coverage
- pip install coveralls
- pip install future

install:

#- conda install matplotlib scipy numpy -y
#- conda install root-numpy rootpy -y
#- pip install rootpy root_numpy
#- conda install py-xgboost -y
- pip install xgboost
#- pip install root_pandas
#- pip install -U xgboost

- pip install -r https://github.com/yandex/rep/raw/master/requirements.txt
- pip install rep
- pip install -U -r requirements.txt
- pip install -U https://github.com/yandex/rep/archive/stratifiedkfold.zip --no-dependencies || pip install -U git+https://github.com/yandex/rep/archive/stratifiedkfold.zip --no-dependencies  # sometimes failes for the first time
- pip install -U git+https://github.com/arogozhnikov/hep_ml.git
- pip install -U xgboost
#- pip install -U -r requirements.txt
#- pip install -U rootpy root_numpy
# - pip install .[root] --no-dependencies
- pip install .[all]
script:
- if [[ "$MAYOU_PYTHON_VERSION" < 3 ]]; then
      coverage run -m unittest discover
    elif [[ "$MAYOU_PYTHON_VERSION >= 3 ]]; then
      python -m unittest discover
  fi


after_success:
 - coveralls

deploy:
  provider: pypi
  user: mayou36
  password:
    secure: mKCnjcpHm5DQHsCcbwo4ahx4Bz5th4gpzXZSQZOhhzs3l1mRxVDYW1GW5FjwSseftjSPXWI3EaDVbLyFP6uwTc0w+HIEeCZMVVKhb9BPWNM/a31uhYfKPwNIORqyvwsq5v4HLg5oyyMlcbNESEx6dStaqlCBOWJUeRq4tZR+R+qttIAH0lWY+QNBc7BB+hTqyZdcYF8iOo5FQBdrfG4rttie1eBEzW1t0TKURnfwx9CryCRfPdKPJi6I4O5gpaTX8h/vAhXQlWGNpSj3EkfZgn//oivnPcwjeQ2Ff8veUShB4fLJ/360xmZEEB3pxBZsb9Beq6iuNOKKtKpXVkWA+i8cPkZ7Y0USwY2quGSZsR0ztthaY8Ju2OqM+YIHchE//jQpMw8OmjcMEplFQZIezzOc/A2W0Zg+MPhFVg4zUxvg7ubHHXEYFGNarGxN2JDIkPfjstX05Stm5aH71zkV2WoyVdb3fpWd9koNJiAaWTHSCMD55pIv90jQG5Rw3Enzi2MfqdXWRs848CqoscaZ8kP4gA/BFDFcXdsP2pWGM829ndqsw0iuDn+tvY/33Dty3NNl+KfBUBrEjO3iSva0M0aIFfj3dZlP57uFK3kdGycDtm6vG5YjAgX1shpu/OiLxxN69p+T+eeDTMaFR4rKc1oLOznhZwojIf6W9aJSXF0=
  distributions: sdist bdist_wheel
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.4" && $TRAVIS_OS_NAME = "linux"
